# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 745a100fabc397d75dd5a4a4c75df005f0cf7febfc219fe74dd60a58018aa50ae6ad82ad2782deb90b41f1394c79b50c40dffe8196856ff10be9f249877dffc9

test:
  secret_key_base: 94b54fa742bad58255eb25bccb363714e191a14ed2417f87ce04fe191c91a312e0942815bcf4766c23013ea5db50242eca2ab13bf11f21afd995094739f7903a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 102f8f402c935fe1a9266e436364e3feaa91280f9f70dbd0fa12a2f9334d6e6c238476dc4ed3cf9fd0f69e4dc2a2d946d02af9e040d54daa71e9f98325c81502